project:
  type: website

website:
  title: "Jackson Vanfleet-Brown"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Graphic design
        href: graphics.qmd
      - text: Writing
        href: writing.qmd
      - text: Resume
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/jackvfb
      - icon: linkedin
        href: https://www.linkedin.com/in/jvfb/
  page-footer:  "Copyright 2024, Jackson Vanfleet-Brown. All rights reserved."

format:
  html:
    theme: yeti
    toc: true
    css: styles.css


