project:
  type: website
  output-dir: docs

website:
  title: "Jackson Vanfleet-Brown"
  navbar:
    left: 
      - text: Experience
        href: cv.qmd
      - text: Portfolio
        href: portfolio.qmd
      - text: Posts
        href: posts.qmd
    right:
      - icon: github
        href: https://github.com/jackvfb
      - icon: linkedin
        href: https://www.linkedin.com/in/jvfb/
  page-footer:  "Copyright 2024, Jackson Vanfleet-Brown. All rights reserved."
  favicon: favicon_j.png

format:
  html:
    theme: yeti
    toc: true
    css: styles.css


