project:
  type: website

website:
  title: "Jackson Vanfleet-Brown"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Thesis
        href: thesis.qmd
    right:
      - icon: github
        href: https://github.com/jackvfb
      - icon: linkedin
        href: https://www.linkedin.com/in/jvfb
format:
  html:
    theme: cosmo
    css: styles.css



