---
title: "Jackson Vanfleet-Brown - CV"
toc-depth: 2
---

I am a new student with an interest in data science. I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.I am a new student with an interest in data science.


## Experience

### Research Intern
[Underwater Acoustic & Navigation Lab](https://sites.google.com/edu.haifa.ac.il/anl/anl), University of Haifa, Israel [2024]{style="float: right;"}

- 6+ years as a research technician serving world-class scientists and engineers across many disciplines. Experienced mariner.


### Environmental diplomacy intern 
[Arava Institute for Environmental Studies](https://arava.org/), Ketura, Israel [2022]{style="float: right;"}

- QC'ed and installed an autonomous water quality monitoring system at West Bank village.
- With minimal training, contributed meaningfully to an ambitious humanitarian project led by US tech startup and international researchers.

### American Samoa Station Chief 
Global Monitoring Laboratory, National Oceanic and Atmospheric Administration (NOAA) [2020 - 2021]{style="float: right;"}

- Learned best mechanical and electrical practices for servicing sophisticated instrument systems while in training at NOAA headquarters in Boulder, Colorado.
- While on-station in American Samoa, a remote Pacific island, I increased data quality and output through excellent management of two locally-based staff.

### Junior bridge watch officer 
NOAA Ship Fairweather, Ketchikan, Alaska [2017 - 2020]{style="float: right;"}

- Led navigational watches aboard 230-ft hydrographic survey vessel.
- Valued member of ship’s command due to breadth of qualifications:
    -   Primary voyage planner for coastal passages from San Diego to the Arctic.
    -   Coxswain of 28-ft small boats.
    -   Multibeam sonar operator.

## Education

### M.S. Marine Science
Estuary and Ocean Science Center, San Francisco State University [2022-2024]{style="float: right;"}

- For thesis research, developed machine learning models to classify dolphin species in passive acoustic recordings.
- Used operational expertise to assist with projects outside my primary research area:
    -   Deployed scientific moorings offshore central California.
    -   Piloted UAV in San Francisco Bay to test new vessel tracking software.
    -   Trailered and coxswained 19-ft boat with two crew sampling zooplankton in San Francisco Estuary.

### B.A. Geology
Carleton College, Northfield, MN, USA [2011-2015]{style="float: right;"}

## Awards

**NOAA Corps Achievement Medal (2019 and 2021)**

Awarded on two occasions by different supervisors for notably positive impact on research operations -- aboard NOAA Ship Fairweather as well as at the NOAA atmospheric observatory in American Samoa.

**Distinction in Geology (2015)**

Awarded by the Carleton College Geology faculty for an exceptional oral presentation of my senior thesis project.

## Training and Qualifications

FAA UAV Remote Pilot (issued 2023)

USCG Master 100 Ton Inland (issued 2023, expires 2028)

Motor Boat Operator (2022) Scientific Boating Safety Association

NOAA Ship Fairweather: Officer of the deck, small boat coxswain, hydrographer-in-charge (2018-2019)
