---
title: "Boot Camp Missive"
subtitle: "A review of my NOAA Corps Indoctrination"
author: Jackson Vanfleet-Brown
date: "2018-01-21"
categories: [creative]
description: "A missive to friends and family upon completion of NOAA Officer basic training"
---

With this message I break the silence that set over me when I entered the NOAA Basic Officer Training Course at the US Coast Guard Academy. It was a long and difficult experience, not one I would want to repeat. I remember lining up at the schoolhouse gates on the day of check-in, turning to the person next to me and telling her I felt like I was on the cusp of entering a haunted house. I left the place one month ago, just numb.

What happened to us at BOTC? The program’s challenges boil down to simple tasks, a schedule, and teamwork. The staff, adept architects of chaotic and stressful situations for the roughly one hundred officer candidates, aim to exercise our abilities as leaders and as followers. Their tactics, developed over the past 50 years, cause the group to collapse under its own weight.

There is a strict daily routine and tardiness immediately becomes a problem for the group. At the sound of reveille, 100 people wake, and in less than ten minutes get dressed for calisthenics, exit the building, form into ranks, take attendance, and deliver reports. In less than five minutes, they serve themselves from a buffet, sit down at tables, pour themselves glasses of water, put napkins in their laps and wait to be granted permission to eat. In less than fifteen minutes, using a very limited number of sinks, toilets, and showers, they all bathe, groom, dress in clean uniforms, and muster outside for personnel inspection. Hopefully this gives you somewhat of an idea of what we do. It is a three part recipe: simple task, plus time limit, plus large group of people.

Not only as a group, but also as individuals, we were placed under enormous stress. We received pages upon pages of dense information known as “required knowledge.” Memorize it. All of it. Verbatim. I was in disbelief until I realized I would not make it through the program without trying. Like ironing clothes, shining boots, and manual of arms, feudal memorization was one of the many activities I reluctantly now espoused. I had to learn, in detail, the biographies of all 18 staff officers, including the dates they reported to each of their past duty stations. I immediately produced answers to questions such as, “When did Ms. Decastro join the NOAA Corps?” All while keeping my eyes in the boat. If I hesitated or stumbled over my words, I had failed.

Much of what we are subjected to depends on us being blinded. And keeping our “eyes in the boat,” accomplishes just that. It is the Coast Guard term for the dead stare that we associate with military recruits in movies and whatnot. In the first month of the program, there were severe consequences for looking—yes, looking—at anything. If we could have looked, we would have seen the imperfections in our staff officers’ uniforms. We would have seen them looking at their clipboards for the Quote of the Day and the time of sunrise. Any movement of the eyes is fiercely rebuked by staff officers for this reason, because restoring our vision would have completely undermined the program’s tenets.

There were many reasons for being reprimanded, besides moving our eyes while in formation, having lint on our uniforms, not knowing required knowledge, and being late. One of the most persistent problems was our inability to properly stow our belongings. All burdened with the same set of articles--6 white shirts, 6 blue shirts, 4 pairs of black socks, 4 pairs of white socks, etc.--living in identical rooms, we had detailed instructions that not only dictated where each item was to be placed but how it was to be folded. It was impossible to fully conform to the manual and our failures gave the staff license to tyrannically overturn our neatly made beds, our carefully arranged drawers. We would arrive at the barracks after class to find our rooms destroyed. For months it went on this way, day in and day out. I still don’t know why it ever stopped.

The point of the program is to exhaust you. When you are tired, rather than give you rest, make you get up earlier. When you are short of time, rather than give you more time, take time away. And when you are hungry, rather than feed you, make it even more difficult for you to eat. To correct performance deficiencies, they make it harder to perform. Any shortcoming is the consequence of your own inadequacy, not the consequence of natural variation in the universe.

We had to do everything as quickly as possible and I soon began to take advantage of every convenience available to me, many of which I would have refrained from using in my past life. I threw everything I didn’t want in the trash can. Used spray-on starch to press my collars and heavily scented laundry soap to keep smells away. Dried my clothes in the machine drier on sunny days. I grasped for anything that made my life easier and faster.

The first several weeks were so taxing that I looked forward to drill practice each evening. Oddly, marching with a rifle felt like some form of recreation. Was this part of the brainwashing? Drill practice meant silence, silence and the idiosyncratic cadence of the platoon leader. Marching sluggishly across the downy lawn, boots swishing with each footstep, our formation leaving a track of three parallel lines of depressed grass. Just on the other side of that spear-tipped iron fence the cars went whizzing by. I was looking through a fence into another world. Careless civilians with strollers munching on bags of chips, glancing furtively. Cars excited by the sight of marching soldiers zealously honking their horns. Everyone stop and plant your guns in the grass and stand stone-faced as the flag is lowered, caught before touching the ground and hugged into a ball.

What purpose did all this serve? The more time passes, the more confused I am by the experience. It appears to have limited applicability to my present job. I am a junior officer on the research ship Fairweather where military customs and courtesies are all but nonexistent. My executive officer is friendly to me, signs notices with a cartoon-like doodle, and encourages me to take time off to take care of myself. NOAA is a scientific agency and military indoctrination seems, for our purposes, to have been a frivolous agony.

The effect of boot camp, however, reached further than indoctrination. I have to give the program credit for being a good simulation of a shipboard living environment. Being in close quarters for an extended period taught me valuable lessons about myself and the way I act within a group. The program aims not to develop obedience but to develop a propensity to use teamwork to solve problems. For every challenge we faced the answer was always, always teamwork. Ship, shipmates, self. In that order. I came to rely solely on my peers for my needs and I left the academy feeling almost no connection to the staff, who I wanted strongly to avoid, even after I realized they were capable of smiling. I used my peers for everything I needed. That was a powerfully transformative result of the program.